### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by stevetrask** [18F/jekyll-get#19]
Hi, I am trying to get this to work, I have added the plugin file and installed required gems, jekyll runs fine without any errors but the data is not displayed on the page or being saved in a file with the cache setting? Am I missing something?

**Comment by budparr** [comment]
Are you using the APIs from the readme page, or your own? Not all of the ones listed here work any longer.

**Comment by stevetrask** [comment]
I am using a different one from a wordpress install - http://www.barn-pub-rest.co.uk/wp-json/wp/v2/posts?per_page=4

**Comment by stevetrask** [comment]
Just to loop back it was an issue with requiring Jekyll 3.0 and thus ruby 2.0

On another question it adds fresh data to the json file on each generation, I presume this is down to the data potentially being slightly different, is there a way to delete the existing data then load in the fresh set?

**Comment by leog** [comment]
Hey @gosupernova. I''m not able to make it work either. Seen that some required gems are not there any more too but I was hoping to know how did you make it work if you did. I'm running over Windows, Jekyll 3.4.3 and Ruby 2.3. Thanks!

**Comment by stevetrask** [comment]
@leog Just making sure I was on the latest Jekyll/ruby fixed my issue, did you manage to fix it? if not do you get any output errors?
