### ISSUE TITLE
make this a gem

### ISSUE THREAD

**Issue by afeld** [18F/jekyll-get#8]
Makes it easier for projects that use this to keep up-to-date. Happy to help if needed.

**Comment by vergilius** [comment]
+1

**Comment by vilbht** [comment]
+1

**Comment by afeld** [comment]
Pull requests for the gemspec, README changes, etc. welcome 😉

**Comment by vilbht** [comment]
+1

**Comment by leog** [comment]
+1

**Comment by Dripdrop12** [comment]
+1

**Comment by benjaminsehl** [comment]
+1

**Comment by JJediny** [comment]
Seems someone published a more updated fork w/ credit to the project:

https://rubygems.org/gems/jekyll-get-json
https://github.com/brockfanning/jekyll-get-json/

Reopen if needed

**Comment by adborden** [comment]
Maybe we should archive this repo if some else has taken over
maintainership.

**Comment by afeld** [comment]
Here goes!
